# Generated by Django 4.1.1 on 2022-09-23 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0004_contest_alter_subscriber_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contest',
            options={'verbose_name': 'Contest', 'verbose_name_plural': 'Contests'},
        ),
    ]
