# Generated by Django 4.1.1 on 2022-09-23 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0008_rename_subscriber_subscribers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribers',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
