# Generated by Django 4.1.1 on 2022-09-24 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0009_alter_subscribers_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribers',
            name='phone_number',
            field=models.CharField(default='0000000000', max_length=128),
        ),
    ]
