# Generated by Django 4.1.1 on 2022-09-24 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0010_subscribers_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='contests',
            name='status',
            field=models.CharField(default='CODING', max_length=128),
        ),
    ]
