# Generated by Django 4.1.1 on 2022-09-25 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0011_contests_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contests',
            name='duration',
            field=models.CharField(max_length=28),
        ),
        migrations.AlterField(
            model_name='contests',
            name='end_time',
            field=models.CharField(max_length=28),
        ),
        migrations.AlterField(
            model_name='contests',
            name='in_24_hours',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='contests',
            name='start_time',
            field=models.CharField(max_length=28),
        ),
        migrations.AlterField(
            model_name='contests',
            name='status',
            field=models.CharField(default='CODING', max_length=8),
        ),
        migrations.AlterField(
            model_name='subscribers',
            name='phone_number',
            field=models.CharField(default='0000000000', max_length=15),
        ),
    ]
